CREATE ROLE CI_CD_ROLE;

CREATE USER GITHUB_CI
PASSWORD='StrongTemporaryPassword123!'
DEFAULT_ROLE=CI_CD_ROLE
DEFAULT_WAREHOUSE=COMPUTE_WH
MUST_CHANGE_PASSWORD=FALSE;

GRANT ROLE CI_CD_ROLE TO USER GITHUB_CI;


GRANT USAGE
ON WAREHOUSE COMPUTE_WH
TO ROLE CI_CD_ROLE;

GRANT USAGE
ON DATABASE DEV
TO ROLE CI_CD_ROLE;

GRANT USAGE
ON ALL SCHEMAS IN DATABASE DEV
TO ROLE CI_CD_ROLE;

GRANT USAGE
ON FUTURE SCHEMAS IN DATABASE DEV
TO ROLE CI_CD_ROLE;

GRANT SELECT
ON ALL TABLES IN DATABASE DEV
TO ROLE CI_CD_ROLE;

GRANT SELECT
ON FUTURE TABLES IN DATABASE DEV
TO ROLE CI_CD_ROLE;


