CREATE OR REPLACE VIEW DEV.GOLD_CUSTOMER.VW_GOLD_CUSTOMER_ENGAGEMENT AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY,
    c.STATE,
    c.COUNTRY,

    COUNT(e.ENGAGEMENT_ID) AS TOTAL_ENGAGEMENTS,

    SUM(
        CASE
            WHEN e.ACTIVITY_TYPE = 'Purchase' THEN 1
            ELSE 0
        END
    ) AS TOTAL_PURCHASES,

    SUM(
        CASE
            WHEN e.ACTIVITY_TYPE = 'Support Ticket' THEN 1
            ELSE 0
        END
    ) AS TOTAL_SUPPORT_TICKETS,

    SUM(e.DURATION_MIN) AS TOTAL_DURATION_MIN,

    MAX(e.ACTIVITY_DT) AS LAST_ACTIVITY_DATE

FROM DEV.GOLD_CUSTOMER.TBL_SLVR_CUSTOMER c
LEFT JOIN DEV.GOLD_CUSTOMER.TBL_SLVR_CUSTOMER_ENGAGEMENT e
    ON c.CUSTOMER_ID = e.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY,
    c.STATE,
    c.COUNTRY;

SELECT CURRENT_ROLE();
