-- Creates a customer recency view showing days since last engagement
CREATE OR REPLACE VIEW VW_GOLD_CUSTOMER_RECENCY AS
SELECT
    CUSTOMER_ID,
    MAX(ACTIVITY_DT) AS LAST_ACTIVITY_DT,
    DATEDIFF('day', MAX(ACTIVITY_DT), CURRENT_DATE()) AS DAYS_SINCE_LAST_ACTIVITY,
    COUNT(ENGAGEMENT_ID) AS TOTAL_ENGAGEMENTS,
    SUM(DURATION_MIN) AS TOTAL_DURATION_MIN
FROM TBL_SLVR_CUSTOMER
GROUP BY CUSTOMER_ID;

