
CREATE OR REPLACE VIEW VW_GOLD_CUSTOMER_ACTIVITY AS
SELECT
    CUSTOMER_ID,
    ACTIVITY_TYPE,
    COUNT(ENGAGEMENT_ID) AS ENGAGEMENT_COUNT,
    SUM(DURATION_MIN) AS TOTAL_DURATION_MIN,
    MIN(ACTIVITY_DT) AS FIRST_ACTIVITY_DT,
    MAX(ACTIVITY_DT) AS LAST_ACTIVITY_DT
FROM TBL_SLVR_CUSTOMER
GROUP BY CUSTOMER_ID, ACTIVITY_TYPE;