name: Deploy to DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: |
          echo "Hello from GitHub Actions!"