name: Deploy to DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Snowflake CLI
        run: |
          pip install snowflake-cli

      - name: Verify Installation
        run: |
          snow --version